---
- import_playbook: ../core/harden.yaml
- import_playbook: ../core/setup.yaml

- hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Ensure pip is installed
      ansible.builtin.apt:
        pkg:
          - python3-pip
          - python3
        state: latest
        update_cache: yes
      async: 600
      poll: 30
