---
- import_playbook: ../core/harden.yaml
- import_playbook: ../core/setup.yaml

- hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Install generic web service packages
      ansible.builtin.apt:
        pkg:
          - pwgen
          - openssl
          - apache2-utils
        state: latest
        update_cache: yes
      async: 900
      poll: 30

    - name: Allow tcp port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow tcp port 443
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
